#ifndef CONFIGURATION_CUSTOM_H
#define CONFIGURATION_CUSTOM_H

#define ENDER_AWESOME
#if ENABLED(ENDER_AWESOME)
  #define ENDER3
  #define LINEAR_ADVANCE
  #define LINEAR_ADVANCE_K 0
  #define SHOW_BOOTSCREEN
  #define SHOW_CUSTOM_BOOTSCREEN
  //#define NEW_JERK_CONTROL
  //#define NEW_ACCELERATION_CONTROL
  #define MANUAL_MESH_LEVELING
  #define USER_PRINTER_NAME "Ender 3"
  #define DICKBUTT_BOOT
#endif

#endif // CONFIGURATION_CUSTOM_H